
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 17 10:35:33 CET 2014
//----------------------------------------------------

package rs.ac.bg.etf.student.pp060115;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREM = 35;
  public static final int MULT = 23;
  public static final int CONST = 14;
  public static final int LESEQU = 32;
  public static final int EQUALS = 26;
  public static final int PERIOD = 39;
  public static final int STRCONST = 20;
  public static final int LPAREN = 40;
  public static final int GREEQU = 30;
  public static final int GREATER = 29;
  public static final int LESS = 31;
  public static final int MINUS = 22;
  public static final int RPAREN = 41;
  public static final int AND = 33;
  public static final int OR = 34;
  public static final int RSQPAREN = 45;
  public static final int COMMA = 38;
  public static final int SEMICOL = 37;
  public static final int CLASS = 8;
  public static final int PLUS = 21;
  public static final int IF = 5;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int PERCENT = 25;
  public static final int NUMBER = 17;
  public static final int BREAK = 7;
  public static final int IDENT = 16;
  public static final int VOID = 13;
  public static final int DEV = 24;
  public static final int LBRACE = 42;
  public static final int ELSE = 6;
  public static final int READ = 4;
  public static final int CHARCONST = 18;
  public static final int WHILE = 11;
  public static final int RBRACE = 43;
  public static final int NOTEQU = 28;
  public static final int BOOLCONST = 19;
  public static final int EXTENDS = 9;
  public static final int DECREM = 36;
  public static final int LSQPAREN = 44;
  public static final int PRINT = 3;
  public static final int DO = 12;
  public static final int EQUEQU = 27;
}

